# Generated by Django 5.2.8 on 2025-11-27 23:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('articulos', '0001_initial'),
        ('compras_ingreso', '0001_initial'),
        ('disponibilidades', '0001_initial'),
        ('documentos', '0001_initial'),
        ('proveedores', '0001_initial'),
        ('tablas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComprasDevolucionesCabezal',
            fields=[
                ('transaccion', models.CharField(help_text='Formato: YYMMXXXXXX (ej: 251100001 para noviembre 2025)', max_length=10, primary_key=True, serialize=False, verbose_name='Transacción')),
                ('serie_documento', models.CharField(max_length=5, null=True, verbose_name='Serie Documento')),
                ('numero_documento', models.CharField(max_length=20, verbose_name='Número Documento')),
                ('fecha_documento', models.DateField(verbose_name='Fecha Documento')),
                ('fecha_movimiento', models.DateTimeField(auto_now_add=True, verbose_name='Fecha Movimiento')),
                ('precio_iva_inc', models.CharField(choices=[('SI', 'Sí'), ('NO', 'No')], default='NO', help_text='Indica si los precios están con IVA incluido o no', max_length=2, verbose_name='Precio con IVA Incluido')),
                ('tipo_compra', models.CharField(choices=[('CONVENCIONAL', 'Convencional'), ('SIMPLIFICADA', 'Simplificada')], default='CONVENCIONAL', help_text='Convencional: con líneas de productos. Simplificada: solo totales manuales', max_length=20, verbose_name='Tipo de Compra')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('monotributista', models.CharField(choices=[('SI', 'Sí'), ('NO', 'No')], default='NO', help_text='Copiado del maestro del proveedor', max_length=2, verbose_name='Monotributista')),
                ('fchhor', models.DateTimeField(auto_now_add=True, verbose_name='Fecha/Hora')),
                ('usuario', models.IntegerField(blank=True, null=True, verbose_name='Usuario')),
                ('sub_total', models.DecimalField(decimal_places=2, default=0, help_text='Suma de sub_total de las líneas', max_digits=15, verbose_name='Sub Total')),
                ('iva', models.DecimalField(decimal_places=2, default=0, help_text='Suma de iva de las líneas', max_digits=15, verbose_name='IVA')),
                ('importe_total', models.DecimalField(decimal_places=2, default=0, help_text='Suma de total de las líneas', max_digits=15, verbose_name='Importe Total')),
                ('disponibilidad', models.ForeignKey(blank=True, help_text='Solo para devoluciones de facturas contado', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='devoluciones_contado', to='disponibilidades.disponibilidad', verbose_name='Disponibilidad')),
                ('forma_pago', models.ForeignKey(db_column='forma_pago', on_delete=django.db.models.deletion.PROTECT, related_name='devoluciones', to='tablas.formapagotipo', verbose_name='Forma de Pago')),
                ('id_proveedor', models.ForeignKey(db_column='id_proveedor', on_delete=django.db.models.deletion.PROTECT, related_name='devoluciones', to='proveedores.proveedor', verbose_name='Proveedor')),
                ('moneda', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='devoluciones', to='articulos.moneda', verbose_name='Moneda')),
                ('tipo_documento', models.ForeignKey(limit_choices_to={'codigo__in': ['ncimpo', 'ncprov', 'devmovprov']}, on_delete=django.db.models.deletion.PROTECT, related_name='devoluciones', to='documentos.documento', verbose_name='Tipo de Documento')),
            ],
            options={
                'verbose_name': 'Devolución Compra Cabezal',
                'verbose_name_plural': 'Devoluciones Compra Cabezal',
                'db_table': 'compras_devoluciones_cabezal',
                'ordering': ['-fchhor', '-transaccion'],
            },
        ),
        migrations.CreateModel(
            name='ComprasDevolucionesLineas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('linea', models.IntegerField(help_text='Número de línea (1, 2, 3...)', verbose_name='Línea')),
                ('serie_doc_afectado', models.CharField(blank=True, help_text='Serie del documento de compra afectado (calculado desde id_compra_linea)', max_length=20, null=True, verbose_name='Serie Doc Afectado')),
                ('numero_doc_afectado', models.CharField(blank=True, help_text='Número del documento de compra afectado (calculado desde id_compra_linea)', max_length=50, verbose_name='Número Doc Afectado')),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Cantidad')),
                ('precio', models.DecimalField(decimal_places=2, help_text='Precio con IVA incluido si el cabezal lo indica, sino sin IVA', max_digits=15, verbose_name='Precio Original')),
                ('sub_total', models.DecimalField(decimal_places=2, help_text='Calculado según si el cabezal tiene IVA incluido o no', max_digits=15, verbose_name='Sub Total')),
                ('iva', models.DecimalField(decimal_places=2, help_text='Calculado según si el cabezal tiene IVA incluido o no', max_digits=15, verbose_name='IVA')),
                ('total', models.DecimalField(decimal_places=2, help_text='sub_total + iva', max_digits=15, verbose_name='Total')),
                ('id_articulo', models.ForeignKey(db_column='id_articulo', on_delete=django.db.models.deletion.PROTECT, related_name='devoluciones_lineas', to='articulos.articulo', verbose_name='Artículo')),
                ('id_compra_linea', models.ForeignKey(blank=True, help_text='Línea específica de la factura de compra afectada (opcional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devoluciones', to='compras_ingreso.compraslineas', verbose_name='Línea de Compra')),
                ('transaccion', models.ForeignKey(db_column='transaccion', on_delete=django.db.models.deletion.CASCADE, related_name='lineas', to='compras_devoluciones.comprasdevolucionescabezal', verbose_name='Transacción')),
            ],
            options={
                'verbose_name': 'Compra Línea',
                'verbose_name_plural': 'Compras Líneas',
                'db_table': 'compras_devoluciones_lineas',
                'ordering': ['transaccion', 'linea'],
                'unique_together': {('transaccion', 'linea')},
            },
        ),
    ]
