# Generated by Django 5.2.8 on 2025-11-23 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compras_devoluciones', '0001_sync_tables_with_models'),
    ]

    operations = [
    ]
