# Generated by Django 5.2.8 on 2025-11-28 11:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ventas_devoluciones', '0001_initial'),
        ('ventas_ingreso', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ventasdevolucioneslineas',
            name='id_venta_linea',
            field=models.ForeignKey(blank=True, help_text='Línea específica de la factura de venta afectada (opcional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devoluciones', to='ventas_ingreso.ventaslineas', verbose_name='Línea de Venta'),
        ),
        migrations.AddField(
            model_name='ventasdevolucioneslineas',
            name='transaccion',
            field=models.ForeignKey(db_column='transaccion', on_delete=django.db.models.deletion.CASCADE, related_name='lineas', to='ventas_devoluciones.ventasdevolucionescabezal', verbose_name='Transacción'),
        ),
        migrations.AlterUniqueTogether(
            name='ventasdevolucioneslineas',
            unique_together={('transaccion', 'linea')},
        ),
    ]
