# Generated by Django 5.2.8 on 2025-11-28 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ventas_devoluciones', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ventasdevolucionescabezal',
            name='monotributista',
        ),
    ]
