# Generated by Django 5.2.8 on 2025-12-01 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ventas_devoluciones", "0003_remove_ventasdevolucionescabezal_monotributista"),
    ]

    operations = [
        migrations.AddField(
            model_name="ventasdevolucionescabezal",
            name="monotributista",
            field=models.CharField(
                choices=[("SI", "Sí"), ("NO", "No")],
                default="NO",
                help_text="Copiado del maestro del cliente",
                max_length=2,
                verbose_name="Monotributista",
            ),
        ),
    ]
