# Generated by Django 5.2.8 on 2025-11-18 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empresa', models.IntegerField(default=1, verbose_name='Empresa')),
                ('codigo', models.IntegerField(blank=True, null=True, unique=True, verbose_name='Código')),
                ('razon', models.CharField(blank=True, max_length=200, null=True, verbose_name='Razón Social')),
                ('razon2', models.CharField(blank=True, max_length=200, null=True, verbose_name='Razón Social 2')),
                ('rut', models.BigIntegerField(blank=True, null=True, verbose_name='RUT')),
                ('domicilio', models.CharField(blank=True, max_length=200, null=True, verbose_name='Domicilio')),
                ('ineloc', models.IntegerField(blank=True, null=True, verbose_name='Código Localidad')),
                ('inedep', models.IntegerField(blank=True, null=True, verbose_name='Código Departamento')),
                ('telefono', models.CharField(blank=True, max_length=50, null=True, verbose_name='Teléfono')),
                ('celular', models.CharField(blank=True, max_length=50, null=True, verbose_name='Celular')),
                ('contacto', models.CharField(blank=True, max_length=200, null=True, verbose_name='Contacto')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('formadepago', models.IntegerField(default=1, verbose_name='Forma de Pago')),
                ('moneda', models.IntegerField(default=858, verbose_name='Moneda')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('activo', models.CharField(choices=[('SI', 'Sí'), ('NO', 'No')], default='SI', max_length=2, verbose_name='Activo')),
                ('fchhor', models.DateTimeField(auto_now=True, verbose_name='Fecha/Hora')),
                ('usuario', models.IntegerField(blank=True, null=True, verbose_name='Usuario')),
                ('monotributista', models.CharField(blank=True, choices=[('SI', 'Sí'), ('NO', 'No'), ('SD', 'Sin Definir')], max_length=2, null=True, verbose_name='Monotributista')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['razon'],
            },
        ),
    ]
