# Generated by Django 5.2.8 on 2025-11-19 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clientes", "0004_remove_cliente_ineloc_cliente_pais_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="FormaPago",
            fields=[
                (
                    "codigo",
                    models.CharField(
                        help_text="Código interno (ej: 30_DIAS, MES_COMPRA_15_DIAS)",
                        max_length=50,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name="ID Forma de Pago",
                    ),
                ),
                (
                    "descripcion",
                    models.CharField(max_length=200, verbose_name="Descripción"),
                ),
                (
                    "plazo_en_dias",
                    models.IntegerField(
                        help_text="Cantidad de días a sumar (0 para contado o no asignada)",
                        verbose_name="Plazo en días",
                    ),
                ),
                (
                    "fin_de_mes",
                    models.BooleanField(
                        default=False,
                        help_text="Si es verdadero, el cálculo se hace desde fin de mes + plazo_en_dias",
                        verbose_name="Desde fin de mes",
                    ),
                ),
            ],
            options={
                "verbose_name": "Forma de Pago",
                "verbose_name_plural": "Formas de Pago",
                "ordering": ["codigo"],
            },
        ),
    ]
