# Generated by Django 5.2.8 on 2025-11-19 00:11

from django.db import migrations, models


def copiar_datos_proveedores(apps, schema_editor):
    """Copiar datos de razon2 a nombre_comercial y establecer valores por defecto"""
    Proveedor = apps.get_model('proveedores', 'Proveedor')
    for proveedor in Proveedor.objects.all():
        # Copiar razon2 a nombre_comercial si existe
        if proveedor.razon2:
            proveedor.nombre_comercial = proveedor.razon2
        elif proveedor.razon:
            # Si no hay razon2, usar razon como nombre_comercial
            proveedor.nombre_comercial = proveedor.razon
        else:
            proveedor.nombre_comercial = 'Sin nombre'
        
        # Establecer monotributista por defecto si es null
        if not proveedor.monotributista:
            proveedor.monotributista = 'NO'
        
        # Establecer razon si es null
        if not proveedor.razon:
            proveedor.razon = proveedor.nombre_comercial or 'Sin razón social'
        
        proveedor.save()


def revertir_datos_proveedores(apps, schema_editor):
    """Revertir los cambios de datos"""
    Proveedor = apps.get_model('proveedores', 'Proveedor')
    for proveedor in Proveedor.objects.all():
        if proveedor.nombre_comercial:
            proveedor.razon2 = proveedor.nombre_comercial
        proveedor.save()


class Migration(migrations.Migration):

    dependencies = [
        ("proveedores", "0001_initial"),
    ]

    operations = [
        # Agregar nuevos campos como nullable primero
        migrations.AddField(
            model_name='proveedor',
            name='nombre_comercial',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Nombre Comercial'),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='pais',
            field=models.CharField(choices=[('UY', 'Uruguay'), ('AR', 'Argentina'), ('BR', 'Brasil'), ('PY', 'Paraguay'), ('BO', 'Bolivia'), ('CL', 'Chile'), ('PE', 'Perú'), ('EC', 'Ecuador'), ('CO', 'Colombia'), ('VE', 'Venezuela'), ('MX', 'México'), ('US', 'Estados Unidos'), ('ES', 'España'), ('IT', 'Italia'), ('FR', 'Francia'), ('DE', 'Alemania'), ('CN', 'China'), ('JP', 'Japón'), ('OTRO', 'Otro')], default='UY', max_length=10, verbose_name='País'),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='departamento',
            field=models.CharField(blank=True, choices=[('1', 'Artigas'), ('2', 'Canelones'), ('3', 'Cerro Largo'), ('4', 'Colonia'), ('5', 'Durazno'), ('6', 'Flores'), ('7', 'Florida'), ('8', 'Lavalleja'), ('9', 'Maldonado'), ('10', 'Montevideo'), ('11', 'Paysandú'), ('12', 'Río Negro'), ('13', 'Rivera'), ('14', 'Rocha'), ('15', 'Salto'), ('16', 'San José'), ('17', 'Soriano'), ('18', 'Tacuarembó'), ('19', 'Treinta y Tres')], max_length=2, null=True, verbose_name='Departamento'),
        ),
        
        # Cambiar tipo de codigo
        migrations.AlterField(
            model_name='proveedor',
            name='codigo',
            field=models.CharField(blank=True, help_text='Formato: PROVV0000001', max_length=20, null=True, unique=True, verbose_name='Código'),
        ),
        
        # Cambiar formadepago a CharField
        migrations.AlterField(
            model_name='proveedor',
            name='formadepago',
            field=models.CharField(choices=[('30_DIAS', '30 DIAS'), ('45_DIAS', '45 DIAS'), ('60_DIAS', '60 Dias'), ('A_35_DIAS', 'A 35 días'), ('CONTADO', 'Contado'), ('CREDITO_15_DIAS', 'Credito 15 dias'), ('CREDITO_2_DIAS', 'Crédito 2 Días'), ('CREDITO_8_DIAS', 'Credito 8 Dias'), ('MES_COMPRA_15_DIAS', 'Mes de Compra y 15 Dias'), ('MES_COMPRA_30_DIAS', 'Mes de Compra y 30 Dias'), ('MES_COMPRA_45_DIAS', 'Mes de Compra y 45 Dias'), ('MES_COMPRA_60_DIAS', 'Mes de Compra y 60 dias'), ('NO_ASIGNADA', 'No Asignada'), ('VENCIMIENTO_PACTADO', 'Vencimiento Pactado')], default='NO_ASIGNADA', max_length=30, verbose_name='Forma de Pago'),
        ),
        
        # Cambiar monotributista
        migrations.AlterField(
            model_name='proveedor',
            name='monotributista',
            field=models.CharField(choices=[('SI', 'Sí'), ('NO', 'No')], default='NO', max_length=2, verbose_name='Monotributista'),
        ),
        
        # Copiar datos
        migrations.RunPython(copiar_datos_proveedores, revertir_datos_proveedores),
        
        # Eliminar campos que ya no se usan
        migrations.RemoveField(
            model_name='proveedor',
            name='razon2',
        ),
        migrations.RemoveField(
            model_name='proveedor',
            name='moneda',
        ),
        migrations.RemoveField(
            model_name='proveedor',
            name='ineloc',
        ),
        migrations.RemoveField(
            model_name='proveedor',
            name='inedep',
        ),
    ]
