# Generated by Django 5.2.8 on 2025-11-19 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("proveedores", "0002_auto_20251118_2111"),
    ]

    operations = [
        migrations.AlterField(
            model_name="proveedor",
            name="codigo",
            field=models.CharField(
                blank=True,
                help_text="Formato: PROV000001",
                max_length=20,
                null=True,
                unique=True,
                verbose_name="Código",
            ),
        ),
        migrations.AlterField(
            model_name="proveedor",
            name="monotributista",
            field=models.CharField(
                blank=True,
                choices=[("SI", "Sí"), ("NO", "No")],
                default="NO",
                max_length=2,
                null=True,
                verbose_name="Monotributista",
            ),
        ),
    ]
