# Generated by Django 5.2.8 on 2025-11-27 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('codigo', models.CharField(help_text='Código único del documento (ej: transbu, valenobr)', max_length=20, primary_key=True, serialize=False, unique=True, verbose_name='Código')),
                ('nombre', models.CharField(help_text='Nombre completo del documento', max_length=200, verbose_name='Nombre')),
                ('descripcion', models.TextField(blank=True, help_text='Descripción opcional del documento', null=True, verbose_name='Descripción')),
                ('activo', models.CharField(choices=[('SI', 'Sí'), ('NO', 'No')], default='SI', help_text='Si el documento está activo o no', max_length=2, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Documento',
                'verbose_name_plural': 'Documentos',
                'db_table': 'config_documentos_maestro',
                'ordering': ['codigo'],
            },
        ),
    ]
