# Generated by Django 5.2.8 on 2025-11-19 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("documentos", "0001_initial"),
    ]

    operations = []
