# Generated by Django 5.2.8 on 2025-11-28 11:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('articulos', '0001_initial'),
        ('clientes', '0001_initial'),
        ('disponibilidades', '0001_initial'),
        ('documentos', '0001_initial'),
        ('tablas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VentasCabezal',
            fields=[
                ('transaccion', models.CharField(help_text='Formato: YYMMXXXXXX (ej: 251100001 para noviembre 2025)', max_length=10, primary_key=True, serialize=False, verbose_name='Transacción')),
                ('serie_documento', models.CharField(blank=True, max_length=20, null=True, verbose_name='Serie Documento')),
                ('numero_documento', models.CharField(max_length=50, verbose_name='Número Documento')),
                ('forma_pago', models.CharField(choices=[('CONTADO', 'Contado'), ('CREDITO', 'Crédito')], max_length=20, verbose_name='Forma de Pago')),
                ('fecha_documento', models.DateField(verbose_name='Fecha Documento')),
                ('fecha_movimiento', models.DateTimeField(auto_now_add=True, verbose_name='Fecha Movimiento')),
                ('precio_iva_inc', models.CharField(choices=[('SI', 'Sí'), ('NO', 'No')], default='NO', help_text='Indica si los precios están con IVA incluido o no', max_length=2, verbose_name='Precio con IVA Incluido')),
                ('plazo', models.CharField(blank=True, help_text='Plazo de pago (solo para crédito). Puede ser el del cliente, "elegir" o "VENCIMIENTO_PACTADO"', max_length=50, null=True, verbose_name='Plazo')),
                ('fecha_vencimiento', models.DateField(blank=True, null=True, verbose_name='Fecha Vencimiento')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('fchhor', models.DateTimeField(auto_now_add=True, verbose_name='Fecha/Hora')),
                ('usuario', models.IntegerField(blank=True, null=True, verbose_name='Usuario')),
                ('tipo_venta', models.CharField(choices=[('CONVENCIONAL', 'Convencional'), ('SIMPLIFICADA', 'Simplificada')], default='CONVENCIONAL', help_text='Convencional: con líneas de productos. Simplificada: solo totales manuales', max_length=20, verbose_name='Tipo de Venta')),
                ('sub_total', models.DecimalField(decimal_places=2, default=0, help_text='Suma de sub_total de las líneas (Convencional) o valor manual (Simplificada)', max_digits=15, verbose_name='Sub Total')),
                ('iva', models.DecimalField(decimal_places=2, default=0, help_text='Suma de iva de las líneas (Convencional) o valor manual (Simplificada)', max_digits=15, verbose_name='IVA')),
                ('importe_total', models.DecimalField(decimal_places=2, default=0, help_text='Suma de total de las líneas (Convencional) o valor manual (Simplificada)', max_digits=15, verbose_name='Importe Total')),
                ('disponibilidad', models.ForeignKey(blank=True, help_text='Solo para forma de pago contado', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ventas_contado', to='disponibilidades.disponibilidad', verbose_name='Disponibilidad')),
                ('id_cliente', models.ForeignKey(db_column='id_cliente', on_delete=django.db.models.deletion.PROTECT, related_name='ventas', to='clientes.cliente', verbose_name='Cliente')),
                ('moneda', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ventas', to='articulos.moneda', verbose_name='Moneda')),
                ('tipo_documento', models.ForeignKey(limit_choices_to={'codigo__in': ['movcli', 'efactura', 'factexpo']}, on_delete=django.db.models.deletion.PROTECT, related_name='ventas', to='documentos.documento', verbose_name='Tipo de Documento')),
            ],
            options={
                'verbose_name': 'Venta Cabezal',
                'verbose_name_plural': 'Ventas Cabezal',
                'db_table': 'ventas_cabezal',
                'ordering': ['-fchhor', '-transaccion'],
            },
        ),
        migrations.CreateModel(
            name='VentasLineas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('linea', models.IntegerField(help_text='Número de línea (1, 2, 3...)', verbose_name='Línea')),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Cantidad')),
                ('precio_original', models.DecimalField(decimal_places=2, help_text='Precio con IVA incluido si el cabezal lo indica, sino sin IVA', max_digits=15, verbose_name='Precio Original')),
                ('descuento', models.DecimalField(decimal_places=2, default=0, help_text='Porcentaje de descuento (ej: 5 para 5%)', max_digits=5, verbose_name='Descuento (%)')),
                ('precio_neto', models.DecimalField(decimal_places=2, help_text='precio_original * (1 - descuento/100)', max_digits=15, verbose_name='Precio Neto')),
                ('sub_total', models.DecimalField(decimal_places=2, help_text='Calculado según si el cabezal tiene IVA incluido o no', max_digits=15, verbose_name='Sub Total')),
                ('iva', models.DecimalField(decimal_places=2, help_text='Calculado según si el cabezal tiene IVA incluido o no', max_digits=15, verbose_name='IVA')),
                ('total', models.DecimalField(decimal_places=2, help_text='sub_total + iva', max_digits=15, verbose_name='Total')),
                ('id_articulo', models.ForeignKey(db_column='id_articulo', on_delete=django.db.models.deletion.PROTECT, related_name='ventas_lineas', to='articulos.articulo', verbose_name='Artículo')),
                ('transaccion', models.ForeignKey(db_column='transaccion', on_delete=django.db.models.deletion.CASCADE, related_name='lineas', to='ventas_ingreso.ventascabezal', verbose_name='Transacción')),
            ],
            options={
                'verbose_name': 'Venta Línea',
                'verbose_name_plural': 'Ventas Líneas',
                'db_table': 'ventas_lineas',
                'ordering': ['transaccion', 'linea'],
                'unique_together': {('transaccion', 'linea')},
            },
        ),
    ]

