# Generated by Django 5.2.8 on 2025-11-19 15:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("articulos", "0009_moneda_alter_articulo_moneda_venta"),
    ]

    operations = [
        migrations.CreateModel(
            name="Disponibilidad",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "codigo",
                    models.CharField(
                        blank=True,
                        help_text="Formato: BCO000001, IEDE000001, CAJA000001",
                        max_length=10,
                        null=True,
                        unique=True,
                        verbose_name="Código",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("BANCO", "Banco"),
                            ("IEDE", "Institución Emisora de Dinero Electrónico"),
                            ("CAJA", "Caja"),
                        ],
                        help_text="Tipo de disponibilidad",
                        max_length=10,
                        verbose_name="Tipo",
                    ),
                ),
                (
                    "nombre_institucion",
                    models.CharField(
                        help_text='Nombre del banco, IEDE o "Caja"',
                        max_length=200,
                        verbose_name="Nombre Institución",
                    ),
                ),
                (
                    "alias",
                    models.CharField(
                        blank=True,
                        help_text="Alias opcional para identificar la disponibilidad",
                        max_length=100,
                        null=True,
                        verbose_name="Alias",
                    ),
                ),
                (
                    "numero",
                    models.CharField(
                        blank=True,
                        help_text="Número de cuenta (bancos) o número de IEDE (opcional)",
                        max_length=100,
                        null=True,
                        verbose_name="Número",
                    ),
                ),
                (
                    "fecha_creacion",
                    models.DateField(
                        auto_now_add=True, verbose_name="Fecha de Creación"
                    ),
                ),
                (
                    "tipo_cuenta",
                    models.CharField(
                        choices=[
                            ("CC", "Cuenta Corriente"),
                            ("CA", "Caja de Ahorro"),
                            ("NA", "N/A"),
                        ],
                        default="NA",
                        help_text="Solo para bancos: Cuenta Corriente o Caja de Ahorro",
                        max_length=2,
                        verbose_name="Tipo de Cuenta",
                    ),
                ),
                (
                    "chequera",
                    models.CharField(
                        choices=[("SI", "Sí"), ("NO", "No"), ("NA", "N/A")],
                        default="NA",
                        help_text="Solo para bancos: Si tiene chequera o no",
                        max_length=2,
                        verbose_name="Chequera",
                    ),
                ),
                (
                    "activo",
                    models.CharField(
                        choices=[("SI", "Sí"), ("NO", "No")],
                        default="SI",
                        help_text="Si la disponibilidad está activa",
                        max_length=2,
                        verbose_name="Activo",
                    ),
                ),
                (
                    "observaciones",
                    models.TextField(
                        blank=True, null=True, verbose_name="Observaciones"
                    ),
                ),
                (
                    "moneda",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="disponibilidades",
                        to="articulos.moneda",
                        verbose_name="Moneda",
                    ),
                ),
            ],
            options={
                "verbose_name": "Disponibilidad",
                "verbose_name_plural": "Disponibilidades",
                "ordering": ["tipo", "codigo"],
            },
        ),
    ]
