# Generated by Django 5.2.8 on 2025-11-27 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FormaPagoTipo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50, unique=True, verbose_name='Nombre')),
                ('activo', models.CharField(choices=[('SI', 'Sí'), ('NO', 'No')], default='SI', max_length=2, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Tipo de Forma de Pago',
                'verbose_name_plural': 'Tipos de Forma de Pago',
                'db_table': 'config_forma_pago',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='PlazoPago',
            fields=[
                ('codigo', models.CharField(help_text='Código interno (ej: 30_DIAS, MES_COMPRA_15_DIAS)', max_length=50, primary_key=True, serialize=False, unique=True, verbose_name='Código')),
                ('descripcion', models.CharField(max_length=200, verbose_name='Descripción')),
                ('plazo_en_dias', models.IntegerField(help_text='Cantidad de días a sumar (0 para contado o no asignada)', verbose_name='Plazo en días')),
                ('fin_de_mes', models.BooleanField(default=False, help_text='Si es verdadero, el cálculo se hace desde fin de mes + plazo_en_dias', verbose_name='Desde fin de mes')),
            ],
            options={
                'verbose_name': 'Plazo de Pago',
                'verbose_name_plural': 'Plazos de Pago',
                'db_table': 'config_plazo_pago',
                'ordering': ['codigo'],
            },
        ),
    ]
