# Generated by Django 5.2.8 on 2025-11-27 23:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('canal_comercial', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormaPago',
            fields=[
                ('codigo', models.CharField(help_text='Código interno (ej: 30_DIAS, MES_COMPRA_15_DIAS)', max_length=50, primary_key=True, serialize=False, unique=True, verbose_name='ID Forma de Pago')),
                ('descripcion', models.CharField(max_length=200, verbose_name='Descripción')),
                ('plazo_en_dias', models.IntegerField(help_text='Cantidad de días a sumar (0 para contado o no asignada)', verbose_name='Plazo en días')),
                ('fin_de_mes', models.BooleanField(default=False, help_text='Si es verdadero, el cálculo se hace desde fin de mes + plazo_en_dias', verbose_name='Desde fin de mes')),
            ],
            options={
                'verbose_name': 'Forma de Pago',
                'verbose_name_plural': 'Formas de Pago',
                'db_table': 'config_formapago',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(blank=True, help_text='Formato: CLI000001', max_length=20, null=True, unique=True, verbose_name='Código')),
                ('nombre_comercial', models.CharField(blank=True, max_length=200, null=True, verbose_name='Nombre Comercial')),
                ('razon_social', models.CharField(blank=True, max_length=200, null=True, verbose_name='Razón Social')),
                ('rut', models.BigIntegerField(blank=True, null=True, verbose_name='RUT')),
                ('domicilio', models.CharField(blank=True, max_length=200, null=True, verbose_name='Domicilio')),
                ('pais', models.CharField(choices=[('UY', 'Uruguay'), ('AR', 'Argentina'), ('BR', 'Brasil'), ('PY', 'Paraguay'), ('BO', 'Bolivia'), ('CL', 'Chile'), ('PE', 'Perú'), ('EC', 'Ecuador'), ('CO', 'Colombia'), ('VE', 'Venezuela'), ('MX', 'México'), ('US', 'Estados Unidos'), ('ES', 'España'), ('IT', 'Italia'), ('FR', 'Francia'), ('DE', 'Alemania'), ('CN', 'China'), ('JP', 'Japón'), ('OTRO', 'Otro')], default='UY', max_length=10, verbose_name='País')),
                ('departamento', models.CharField(blank=True, choices=[('1', 'Artigas'), ('2', 'Canelones'), ('3', 'Cerro Largo'), ('4', 'Colonia'), ('5', 'Durazno'), ('6', 'Flores'), ('7', 'Florida'), ('8', 'Lavalleja'), ('9', 'Maldonado'), ('10', 'Montevideo'), ('11', 'Paysandú'), ('12', 'Río Negro'), ('13', 'Rivera'), ('14', 'Rocha'), ('15', 'Salto'), ('16', 'San José'), ('17', 'Soriano'), ('18', 'Tacuarembó'), ('19', 'Treinta y Tres')], max_length=2, null=True, verbose_name='Departamento')),
                ('telefono', models.CharField(blank=True, max_length=50, null=True, verbose_name='Teléfono')),
                ('celular', models.CharField(blank=True, max_length=50, null=True, verbose_name='Celular')),
                ('contacto', models.CharField(blank=True, max_length=200, null=True, verbose_name='Contacto')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('forma_pago', models.CharField(choices=[('30_DIAS', '30 DIAS'), ('45_DIAS', '45 DIAS'), ('60_DIAS', '60 Dias'), ('A_35_DIAS', 'A 35 días'), ('CONTADO', 'Contado'), ('CREDITO_15_DIAS', 'Credito 15 dias'), ('CREDITO_2_DIAS', 'Crédito 2 Días'), ('CREDITO_8_DIAS', 'Credito 8 Dias'), ('MES_COMPRA_15_DIAS', 'Mes de Compra y 15 Dias'), ('MES_COMPRA_30_DIAS', 'Mes de Compra y 30 Dias'), ('MES_COMPRA_45_DIAS', 'Mes de Compra y 45 Dias'), ('MES_COMPRA_60_DIAS', 'Mes de Compra y 60 dias'), ('NO_ASIGNADA', 'No Asignada'), ('VENCIMIENTO_PACTADO', 'Vencimiento Pactado')], default='NO_ASIGNADA', max_length=30, verbose_name='Forma de Pago')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('activo', models.CharField(choices=[('SI', 'Sí'), ('NO', 'No')], default='SI', max_length=2, verbose_name='Activo')),
                ('fchhor', models.DateTimeField(auto_now=True, verbose_name='Fecha/Hora')),
                ('usuario', models.IntegerField(blank=True, null=True, verbose_name='Usuario')),
                ('monotributista', models.CharField(blank=True, choices=[('SI', 'Sí'), ('NO', 'No')], default='NO', max_length=2, null=True, verbose_name='Monotributista')),
                ('canal_comercial', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clientes', to='canal_comercial.canalcomercial', verbose_name='Canal Comercial')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'db_table': 'config_cliente_maestro',
                'ordering': ['nombre_comercial'],
            },
        ),
    ]
