# Generated by Django 5.2.8 on 2025-11-18 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cliente',
            options={'ordering': ['nombre_comercial'], 'verbose_name': 'Cliente', 'verbose_name_plural': 'Clientes'},
        ),
        migrations.RenameField(
            model_name='cliente',
            old_name='razon',
            new_name='razon_social',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='empresa',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='formadepago',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='inedep',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='moneda',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='razon2',
        ),
        migrations.AddField(
            model_name='cliente',
            name='departamento',
            field=models.CharField(blank=True, choices=[('1', 'Artigas'), ('2', 'Canelones'), ('3', 'Cerro Largo'), ('4', 'Colonia'), ('5', 'Durazno'), ('6', 'Flores'), ('7', 'Florida'), ('8', 'Lavalleja'), ('9', 'Maldonado'), ('10', 'Montevideo'), ('11', 'Paysandú'), ('12', 'Río Negro'), ('13', 'Rivera'), ('14', 'Rocha'), ('15', 'Salto'), ('16', 'San José'), ('17', 'Soriano'), ('18', 'Tacuarembó'), ('19', 'Treinta y Tres')], max_length=2, null=True, verbose_name='Departamento'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='forma_pago',
            field=models.CharField(choices=[('30_DIAS', '30 DIAS'), ('45_DIAS', '45 DIAS'), ('60_DIAS', '60 Dias'), ('A_35_DIAS', 'A 35 días'), ('CONTADO', 'Contado'), ('CREDITO_15_DIAS', 'Credito 15 dias'), ('CREDITO_2_DIAS', 'Crédito 2 Días'), ('CREDITO_8_DIAS', 'Credito 8 Dias'), ('MES_COMPRA_15_DIAS', 'Mes de Compra y 15 Dias'), ('MES_COMPRA_30_DIAS', 'Mes de Compra y 30 Dias'), ('MES_COMPRA_45_DIAS', 'Mes de Compra y 45 Dias'), ('MES_COMPRA_60_DIAS', 'Mes de Compra y 60 dias'), ('NO_ASIGNADA', 'No Asignada'), ('VENCIMIENTO_PACTADO', 'Vencimiento Pactado')], default='NO_ASIGNADA', max_length=30, verbose_name='Forma de Pago'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='nombre_comercial',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Nombre Comercial'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='codigo',
            field=models.CharField(blank=True, help_text='Formato: CLI000001', max_length=20, null=True, unique=True, verbose_name='Código'),
        ),
    ]
