# Generated by Django 5.2.8 on 2025-11-18 22:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canal_comercial', '0001_initial'),
        ('clientes', '0002_alter_cliente_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='canal_comercial',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clientes', to='canal_comercial.canalcomercial', verbose_name='Canal Comercial'),
        ),
    ]
