# Generated by Django 5.2.8 on 2025-11-19 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clientes", "0003_cliente_canal_comercial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cliente",
            name="ineloc",
        ),
        migrations.AddField(
            model_name="cliente",
            name="pais",
            field=models.CharField(
                choices=[
                    ("UY", "Uruguay"),
                    ("AR", "Argentina"),
                    ("BR", "Brasil"),
                    ("PY", "Paraguay"),
                    ("BO", "Bolivia"),
                    ("CL", "Chile"),
                    ("PE", "Perú"),
                    ("EC", "Ecuador"),
                    ("CO", "Colombia"),
                    ("VE", "Venezuela"),
                    ("MX", "México"),
                    ("US", "Estados Unidos"),
                    ("ES", "España"),
                    ("IT", "Italia"),
                    ("FR", "Francia"),
                    ("DE", "Alemania"),
                    ("CN", "China"),
                    ("JP", "Japón"),
                    ("OTRO", "Otro"),
                ],
                default="UY",
                max_length=10,
                verbose_name="País",
            ),
        ),
        migrations.AlterField(
            model_name="cliente",
            name="monotributista",
            field=models.CharField(
                blank=True,
                choices=[("SI", "Sí"), ("NO", "No")],
                default="NO",
                max_length=2,
                null=True,
                verbose_name="Monotributista",
            ),
        ),
    ]
