# Generated by Django 5.2.8 on 2025-11-27 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Deposito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre del depósito', max_length=200, verbose_name='Nombre')),
                ('explicacion', models.TextField(blank=True, help_text='Descripción o explicación del depósito', null=True, verbose_name='Explicación')),
            ],
            options={
                'verbose_name': 'Depósito',
                'verbose_name_plural': 'Depósitos',
                'ordering': ['nombre'],
            },
        ),
    ]
