# Generated by Django 5.2.8 on 2025-11-27 23:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('articulos', '0001_initial'),
        ('industria_le_stage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id_equipo', models.AutoField(db_column='id_equipo', primary_key=True, serialize=False, verbose_name='ID Equipo')),
                ('nombre_equipo', models.CharField(max_length=200, verbose_name='Nombre Equipo')),
                ('responsable', models.CharField(max_length=200, verbose_name='Responsable')),
            ],
            options={
                'verbose_name': 'Equipo',
                'verbose_name_plural': 'Equipos',
                'db_table': 'mineria_equipos',
                'ordering': ['nombre_equipo'],
            },
        ),
        migrations.CreateModel(
            name='EquipoCorte',
            fields=[
                ('id_equipo', models.AutoField(db_column='id_equipo', primary_key=True, serialize=False, verbose_name='ID Equipo')),
                ('nombre_equipo', models.CharField(max_length=200, verbose_name='Nombre Equipo')),
                ('responsable', models.CharField(max_length=200, verbose_name='Responsable')),
            ],
            options={
                'verbose_name': 'Equipo Corte',
                'verbose_name_plural': 'Equipos Corte',
                'db_table': 'mineria_equipos_corte',
                'ordering': ['nombre_equipo'],
            },
        ),
        migrations.CreateModel(
            name='PiedrasCanteras',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('kpi', models.CharField(choices=[('Kg', 'Kilogramos'), ('Valuación', 'Valuación')], help_text='Indica si el puntaje se calcula por kilos o por valuación', max_length=20, verbose_name='KPI')),
                ('puntos', models.DecimalField(decimal_places=2, help_text='Puntos por defecto (sugerencia para equipos)', max_digits=15, verbose_name='Puntos')),
                ('familia_producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='piedras_canteras', to='articulos.familia', verbose_name='Familia de Producto')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='piedras_canteras', to='articulos.articulo', verbose_name='Producto (Piedra)')),
            ],
            options={
                'verbose_name': 'Piedra/Cantera',
                'verbose_name_plural': 'Piedras/Canteras',
                'db_table': 'mineria_piedras_canteras',
                'ordering': ['familia_producto', 'producto'],
                'unique_together': {('familia_producto', 'producto')},
            },
        ),
        migrations.CreateModel(
            name='PiezasCorteCantera',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_piedra', models.CharField(blank=True, max_length=200, verbose_name='Nombre Piedra')),
                ('numero', models.CharField(blank=True, max_length=100, verbose_name='Número')),
                ('fecha_extraccion', models.DateField(blank=True, null=True, verbose_name='Fecha Extracción')),
                ('kilos_en_cantera', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Kilos en Cantera')),
                ('valuacion_cantera', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Valuación Cantera')),
                ('porcentaje_valuacion_corte', models.DecimalField(decimal_places=2, default=0, help_text='Porcentaje (ej: 15.50 para 15.5%)', max_digits=5, verbose_name='% de Valuación para Equipo de Corte')),
                ('ganancia_equipo_corte', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Ganancia Equipo de Corte')),
                ('fecha_industria', models.DateField(blank=True, null=True, verbose_name='Fecha Industria')),
                ('kilos_recepcion_industria', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Kilos en Recepción Industria')),
                ('tipo_piedra', models.CharField(blank=True, choices=[('Ágata', 'Ágata'), ('Amatista', 'Amatista')], max_length=200, verbose_name='Tipo de Piedra')),
                ('kilos_despues_tallado', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Kilos después del Tallado')),
                ('precio_por_kilo_tallado', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Precio por Kilo de Tallado')),
                ('pulido_por_kilo', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Pulido por Kilo')),
                ('extra_carlos', models.CharField(blank=True, max_length=200, verbose_name='Extra Carlos')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de Modificación')),
                ('equipo_corte', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='piezas_corte_cantera_corte', to='mineria_le_stage.equipocorte', verbose_name='Equipo de Corte')),
                ('equipo_minero', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='piezas_corte_cantera_minero', to='mineria_le_stage.equipo', verbose_name='Equipo Minero')),
                ('tipo_proceso', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='piezas_corte_cantera', to='industria_le_stage.tipopulidopiezas', verbose_name='Tipos de Pulido Piezas')),
            ],
            options={
                'verbose_name': 'Pieza Corte Cantera',
                'verbose_name_plural': 'Piezas Corte Cantera',
                'db_table': 'mineria_piezas_corte_cantera',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='Costos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(help_text='Primer día del mes (ej: 2025-11-01 para noviembre 2025)', verbose_name='Fecha')),
                ('rubro', models.CharField(choices=[('Producciones', 'Producciones'), ('Sueldos', 'Sueldos'), ('Combustible', 'Combustible'), ('Insumos', 'Insumos'), ('Apoyo', 'Apoyo'), ('Explosivos', 'Explosivos'), ('Otros', 'Otros')], max_length=50, verbose_name='Rubro')),
                ('costo_dolares', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Costo en Dólares')),
                ('id_equipo', models.ForeignKey(db_column='id_equipo', on_delete=django.db.models.deletion.PROTECT, related_name='costos', to='mineria_le_stage.equipo', verbose_name='Equipo')),
            ],
            options={
                'verbose_name': 'Costo',
                'verbose_name_plural': 'Costos',
                'db_table': 'mineria_costos',
                'ordering': ['id_equipo', '-fecha', 'rubro'],
                'unique_together': {('id_equipo', 'fecha', 'rubro')},
            },
        ),
        migrations.CreateModel(
            name='ProduccionEquipo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('mes_año', models.DateField(help_text='Primer día del mes (ej: 2025-11-01 para noviembre 2025)', verbose_name='Mes/Año')),
                ('puntos', models.DecimalField(decimal_places=2, help_text='Puntos editables (por defecto de PiedrasCanteras, pero el usuario puede cambiarlos)', max_digits=15, verbose_name='Puntos')),
                ('valuacion', models.DecimalField(decimal_places=2, default=0, help_text='Valuación en dinero', max_digits=15, verbose_name='Valor Monetario')),
                ('kilos', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Kilos')),
                ('puntos_calculados', models.DecimalField(decimal_places=2, default=0, help_text='Calculado automáticamente: kilos × puntos (si KPI es Kg) o valuacion × puntos (si KPI es Valuación)', max_digits=15, verbose_name='Puntos Calculados')),
                ('id_equipo', models.ForeignKey(db_column='id_equipo', on_delete=django.db.models.deletion.PROTECT, related_name='producciones', to='mineria_le_stage.equipo', verbose_name='Equipo')),
                ('piedra_cantera', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='producciones_equipos', to='mineria_le_stage.piedrascanteras', verbose_name='Piedra/Cantera')),
            ],
            options={
                'verbose_name': 'Producción Equipo',
                'verbose_name_plural': 'Producciones Equipos',
                'db_table': 'mineria_produccion_equipos',
                'ordering': ['id_equipo', '-mes_año', 'piedra_cantera'],
                'unique_together': {('mes_año', 'id_equipo', 'piedra_cantera')},
            },
        ),
    ]
