# Generated by Django 5.2.8 on 2025-11-19 00:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("articulos", "0003_restructurar_articulos"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="articulo",
            name="activo",
        ),
        migrations.RemoveField(
            model_name="articulo",
            name="arcodigo",
        ),
        migrations.RemoveField(
            model_name="articulo",
            name="ardescri",
        ),
        migrations.RemoveField(
            model_name="articulo",
            name="arid",
        ),
        migrations.RemoveField(
            model_name="articulo",
            name="grupo",
        ),
        migrations.RemoveField(
            model_name="articulo",
            name="prcosto",
        ),
        migrations.RemoveField(
            model_name="articulo",
            name="prventa",
        ),
        migrations.RemoveField(
            model_name="articulo",
            name="stock",
        ),
        migrations.RemoveField(
            model_name="articulo",
            name="stock_minimo",
        ),
        migrations.RemoveField(
            model_name="articulo",
            name="subgrupo",
        ),
        migrations.RemoveField(
            model_name="articulo",
            name="tpoiva",
        ),
        migrations.RemoveField(
            model_name="articulo",
            name="unidad_medida",
        ),
        migrations.RemoveField(
            model_name="articulo",
            name="usuario",
        ),
    ]
