# Generated by Django 5.2.8 on 2025-11-19 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articulos", "0005_tipoarticulo_loteable"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="familia",
            options={
                "ordering": ["codigo"],
                "verbose_name": "Familia",
                "verbose_name_plural": "Familias",
            },
        ),
        migrations.AlterModelOptions(
            name="subfamilia",
            options={
                "ordering": ["codigo"],
                "verbose_name": "Sub Familia",
                "verbose_name_plural": "Sub Familias",
            },
        ),
        migrations.AddField(
            model_name="familia",
            name="codigo",
            field=models.CharField(
                blank=True,
                help_text="Formato: FAM001",
                max_length=20,
                null=True,
                unique=True,
                verbose_name="Código",
            ),
        ),
        migrations.AddField(
            model_name="familia",
            name="observaciones",
            field=models.TextField(blank=True, null=True, verbose_name="Observaciones"),
        ),
        migrations.AddField(
            model_name="subfamilia",
            name="codigo",
            field=models.CharField(
                blank=True,
                help_text="Formato: SUBFAM001",
                max_length=20,
                null=True,
                unique=True,
                verbose_name="Código",
            ),
        ),
        migrations.AddField(
            model_name="subfamilia",
            name="observaciones",
            field=models.TextField(blank=True, null=True, verbose_name="Observaciones"),
        ),
    ]
