# Generated by Django 5.2.8 on 2025-11-19 00:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articulos", "0006_alter_familia_options_alter_subfamilia_options_and_more"),
        ("proveedores", "0003_alter_proveedor_codigo_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CodigoProveedorCompra",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "codigo_proveedor",
                    models.CharField(
                        help_text="Código que el proveedor usa para este artículo",
                        max_length=100,
                        verbose_name="Código Proveedor",
                    ),
                ),
                (
                    "articulo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="codigos_proveedor",
                        to="articulos.articulo",
                        verbose_name="Artículo",
                    ),
                ),
                (
                    "proveedor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="codigos_articulos",
                        to="proveedores.proveedor",
                        verbose_name="Proveedor",
                    ),
                ),
            ],
            options={
                "verbose_name": "Código Proveedor Compra",
                "verbose_name_plural": "Códigos Proveedor Compra",
                "ordering": ["proveedor", "codigo_proveedor"],
                "unique_together": {("articulo", "proveedor", "codigo_proveedor")},
            },
        ),
    ]
