# Generated by Django 5.2.8 on 2025-11-19 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("articulos", "0007_codigoproveedorcompra"),
        ("proveedores", "0003_alter_proveedor_codigo_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="codigoproveedorcompra",
            unique_together={("articulo", "proveedor")},
        ),
    ]
