# Generated by Django 5.2.8 on 2025-11-19 14:35

import django.db.models.deletion
from django.db import migrations, models


def poblar_monedas(apps, schema_editor):
    """Poblar monedas iniciales"""
    Moneda = apps.get_model('articulos', 'Moneda')
    
    monedas = [
        {'codigo': 'UYU', 'nombre': 'Peso Uruguayo', 'activo': 'SI'},
        {'codigo': 'USD', 'nombre': 'Dólar Estadounidense', 'activo': 'SI'},
        {'codigo': 'UI', 'nombre': 'Unidad Indexada', 'activo': 'SI'},
        {'codigo': 'EUR', 'nombre': 'Euro', 'activo': 'SI'},
        {'codigo': 'ARG', 'nombre': 'Peso Argentino', 'activo': 'SI'},
        {'codigo': 'BRA', 'nombre': 'Real Brasileño', 'activo': 'SI'},
    ]
    
    for moneda_data in monedas:
        Moneda.objects.get_or_create(
            codigo=moneda_data['codigo'],
            defaults={
                'nombre': moneda_data['nombre'],
                'activo': moneda_data['activo']
            }
        )


def migrar_monedas_articulos(apps, schema_editor):
    """Migrar monedas de artículos existentes"""
    Articulo = apps.get_model('articulos', 'Articulo')
    Moneda = apps.get_model('articulos', 'Moneda')
    
    # Obtener moneda por defecto (UYU)
    moneda_default = Moneda.objects.filter(codigo='UYU').first()
    
    if moneda_default:
        # Asignar UYU a todos los artículos que no tengan moneda
        Articulo.objects.filter(moneda_venta__isnull=True).update(moneda_venta=moneda_default)


def revertir_migracion(apps, schema_editor):
    """Revertir la migración"""
    Moneda = apps.get_model('articulos', 'Moneda')
    Moneda.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ("articulos", "0008_alter_codigoproveedorcompra_unique_together"),
    ]

    operations = [
        migrations.CreateModel(
            name="Moneda",
            fields=[
                (
                    "codigo",
                    models.CharField(
                        help_text="Código de 3 letras (ej: UYU, USD, EUR)",
                        max_length=3,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name="Código",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        help_text="Nombre completo de la moneda",
                        max_length=100,
                        verbose_name="Nombre",
                    ),
                ),
                (
                    "activo",
                    models.CharField(
                        choices=[("SI", "Sí"), ("NO", "No")],
                        default="SI",
                        help_text="Si la moneda está activa o no",
                        max_length=2,
                        verbose_name="Activo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Moneda",
                "verbose_name_plural": "Monedas",
                "ordering": ["codigo"],
            },
        ),
        migrations.AlterField(
            model_name="articulo",
            name="moneda_venta",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="articulos",
                to="articulos.moneda",
                verbose_name="Moneda de Venta",
            ),
        ),
        # Poblar monedas iniciales
        migrations.RunPython(poblar_monedas, revertir_migracion),
        # Migrar monedas de artículos existentes
        migrations.RunPython(migrar_monedas_articulos, migrations.RunPython.noop),
    ]
