# Generated by Django 5.2.8 on 2025-11-19 21:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articulos", "0009_moneda_alter_articulo_moneda_venta"),
    ]

    operations = [
        migrations.CreateModel(
            name="IVA",
            fields=[
                (
                    "codigo",
                    models.CharField(
                        help_text="Código interno del IVA (ej: iva_b, iva_m, exento)",
                        max_length=10,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name="Código",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        help_text="Nombre del IVA (ej: IVA Básico, IVA Mínimo, Exento)",
                        max_length=100,
                        verbose_name="Nombre",
                    ),
                ),
                (
                    "valor",
                    models.DecimalField(
                        decimal_places=4,
                        help_text="Valor como proporción (ej: 0.22 para 22%)",
                        max_digits=5,
                        verbose_name="Valor",
                    ),
                ),
                (
                    "activo",
                    models.CharField(
                        choices=[("SI", "Sí"), ("NO", "No")],
                        default="SI",
                        help_text="Si la tasa de IVA está activa o no",
                        max_length=2,
                        verbose_name="Activo",
                    ),
                ),
            ],
            options={
                "verbose_name": "IVA",
                "verbose_name_plural": "IVAs",
                "ordering": ["codigo"],
            },
        ),
        migrations.AddField(
            model_name="articulo",
            name="iva",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="articulos",
                to="articulos.iva",
                verbose_name="IVA",
            ),
        ),
    ]
