# Generated by Django 5.2.8 on 2025-11-27 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TipoPulidoPiezas',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, unique=True, verbose_name='Nombre')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
            ],
            options={
                'verbose_name': 'Tipo de Pulido Piezas',
                'verbose_name_plural': 'Tipos de Pulido Piezas',
                'db_table': 'industria_tipo_pulido_piezas',
                'ordering': ['nombre'],
            },
        ),
    ]
