# Generated by Django 5.2.8 on 2025-11-27 23:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documentos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaccion',
            fields=[
                ('transaccion', models.CharField(help_text='Formato: AAMMXXXXXX (ej: 251100001 para noviembre 2025)', max_length=10, primary_key=True, serialize=False, verbose_name='Transacción')),
                ('documento_id', models.CharField(blank=True, db_column='documento_id', max_length=20, null=True, verbose_name='Documento ID')),
                ('fecha', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora en que se creó la transacción', verbose_name='Fecha de Creación')),
                ('usuario', models.IntegerField(blank=True, null=True, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Transacción',
                'verbose_name_plural': 'Transacciones',
                'db_table': 'config_transacciones',
                'ordering': ['-fecha', '-transaccion'],
            },
        ),
        migrations.CreateModel(
            name='TransaccionDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referencia_id', models.IntegerField(help_text='ID del documento en su tabla específica (ej: ID de la orden de compra)', verbose_name='ID de Referencia')),
                ('fecha', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('documento', models.ForeignKey(help_text='Tipo de documento (ej: Orden Compra, Factura Venta)', on_delete=django.db.models.deletion.PROTECT, related_name='transacciones', to='documentos.documento', verbose_name='Documento')),
                ('transaccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='transacciones.transaccion', verbose_name='Transacción')),
            ],
            options={
                'verbose_name': 'Transacción Documento',
                'verbose_name_plural': 'Transacciones Documentos',
                'db_table': 'config_transacciondocumento',
                'ordering': ['-fecha'],
                'unique_together': {('documento', 'referencia_id')},
            },
        ),
    ]
