# Generated by Django 5.2.8 on 2025-11-18 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arid', models.IntegerField(blank=True, null=True, unique=True, verbose_name='ID Artículo')),
                ('arcodigo', models.IntegerField(blank=True, null=True, unique=True, verbose_name='Código Artículo')),
                ('ardescri', models.CharField(blank=True, max_length=200, null=True, verbose_name='Descripción')),
                ('grupo', models.IntegerField(blank=True, null=True, verbose_name='Grupo')),
                ('subgrupo', models.IntegerField(blank=True, null=True, verbose_name='Subgrupo')),
                ('unidad_medida', models.CharField(blank=True, max_length=20, null=True, verbose_name='Unidad de Medida')),
                ('prcosto', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Precio Costo')),
                ('prventa', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Precio Venta')),
                ('stock', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Stock')),
                ('stock_minimo', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Stock Mínimo')),
                ('tpoiva', models.IntegerField(default=3, verbose_name='Tipo IVA')),
                ('activo', models.CharField(choices=[('SI', 'Sí'), ('NO', 'No')], default='SI', max_length=2, verbose_name='Activo')),
                ('fchhor', models.DateTimeField(auto_now=True, verbose_name='Fecha/Hora')),
                ('usuario', models.IntegerField(blank=True, null=True, verbose_name='Usuario')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
            ],
            options={
                'verbose_name': 'Artículo',
                'verbose_name_plural': 'Artículos',
                'ordering': ['ardescri'],
            },
        ),
    ]
