# Generated by Django 5.2.8 on 2025-11-27 23:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('proveedores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Familia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(blank=True, help_text='Formato: FAM001', max_length=20, null=True, unique=True, verbose_name='Código')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
            ],
            options={
                'verbose_name': 'Familia',
                'verbose_name_plural': 'Familias',
                'db_table': 'config_articulos_familia',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='IVA',
            fields=[
                ('codigo', models.CharField(help_text='Código interno del IVA (ej: iva_b, iva_m, exento)', max_length=10, primary_key=True, serialize=False, unique=True, verbose_name='Código')),
                ('nombre', models.CharField(help_text='Nombre del IVA (ej: IVA Básico, IVA Mínimo, Exento)', max_length=100, verbose_name='Nombre')),
                ('valor', models.DecimalField(decimal_places=4, help_text='Valor como proporción (ej: 0.22 para 22%)', max_digits=5, verbose_name='Valor')),
                ('activo', models.CharField(choices=[('SI', 'Sí'), ('NO', 'No')], default='SI', help_text='Si la tasa de IVA está activa o no', max_length=2, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'IVA',
                'verbose_name_plural': 'IVAs',
                'db_table': 'config_iva',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='Moneda',
            fields=[
                ('codigo', models.CharField(help_text='Código de 3 letras (ej: UYU, USD, EUR)', max_length=3, primary_key=True, serialize=False, unique=True, verbose_name='Código')),
                ('nombre', models.CharField(help_text='Nombre completo de la moneda', max_length=100, verbose_name='Nombre')),
                ('activo', models.CharField(choices=[('SI', 'Sí'), ('NO', 'No')], default='SI', help_text='Si la moneda está activa o no', max_length=2, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Moneda',
                'verbose_name_plural': 'Monedas',
                'db_table': 'config_moneda',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='TipoArticulo',
            fields=[
                ('codigo', models.CharField(help_text='3 letras representativas (ej: SER, INS, PRO)', max_length=3, primary_key=True, serialize=False, unique=True, verbose_name='Código')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('stockeable', models.CharField(choices=[('SI', 'Sí'), ('NO', 'No')], default='NO', help_text='Si computa stock o no', max_length=2, verbose_name='Stockeable')),
                ('se_compra', models.CharField(choices=[('SI', 'Sí'), ('NO', 'No')], default='SI', help_text='Si se puede comprar este tipo de artículo', max_length=2, verbose_name='Se Compra')),
                ('loteable', models.CharField(choices=[('SI', 'Sí'), ('NO', 'No')], default='NO', help_text='Si este tipo de artículo puede tener lotes', max_length=2, verbose_name='Loteable')),
            ],
            options={
                'verbose_name': 'Tipo de Artículo',
                'verbose_name_plural': 'Tipos de Artículo',
                'db_table': 'config_articulos_tipoarticulo',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='SubFamilia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(blank=True, help_text='Formato: SUBFAM001', max_length=20, null=True, unique=True, verbose_name='Código')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('familia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subfamilias', to='articulos.familia', verbose_name='Familia')),
            ],
            options={
                'verbose_name': 'Sub Familia',
                'verbose_name_plural': 'Sub Familias',
                'db_table': 'config_articulos_subfamilia',
                'ordering': ['codigo'],
                'unique_together': {('familia', 'nombre')},
            },
        ),
        migrations.CreateModel(
            name='Articulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producto_id', models.CharField(blank=True, help_text='Formato: XXX000001 (3 letras del tipo + 6 números)', max_length=10, null=True, unique=True, verbose_name='ID Producto')),
                ('nombre', models.CharField(blank=True, max_length=200, null=True, verbose_name='Nombre')),
                ('precio_venta', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Precio de Venta')),
                ('UNIDAD_VENTA', models.CharField(choices=[('BIDON', 'Bidón'), ('BOLSA', 'Bolsa'), ('CAJA', 'Caja'), ('FRASCO', 'Frasco'), ('GRAMOS', 'Gramos'), ('HECTAREAS', 'Hectáreas'), ('HORAS', 'Horas'), ('KILOMETROS', 'Kilómetros'), ('KILOS', 'Kilos'), ('LITROS', 'Litros'), ('METROS', 'Metros'), ('METROS_CUADRADOS', 'Metros cuadrados'), ('METROS_CUBICOS', 'Metros cúbicos'), ('TONELADAS', 'Toneladas'), ('UNITARIO', 'Unitario')], default='UNITARIO', max_length=20, verbose_name='Unidad de Venta')),
                ('UNIDAD_STOCK', models.CharField(choices=[('BIDON', 'Bidón'), ('BOLSA', 'Bolsa'), ('CAJA', 'Caja'), ('FRASCO', 'Frasco'), ('GRAMOS', 'Gramos'), ('HECTAREAS', 'Hectáreas'), ('HORAS', 'Horas'), ('KILOMETROS', 'Kilómetros'), ('KILOS', 'Kilos'), ('LITROS', 'Litros'), ('METROS', 'Metros'), ('METROS_CUADRADOS', 'Metros cuadrados'), ('METROS_CUBICOS', 'Metros cúbicos'), ('TONELADAS', 'Toneladas'), ('UNITARIO', 'Unitario')], default='UNITARIO', max_length=20, verbose_name='Unidad de Stock')),
                ('UNIDAD_COMPRA', models.CharField(choices=[('BIDON', 'Bidón'), ('BOLSA', 'Bolsa'), ('CAJA', 'Caja'), ('FRASCO', 'Frasco'), ('GRAMOS', 'Gramos'), ('HECTAREAS', 'Hectáreas'), ('HORAS', 'Horas'), ('KILOMETROS', 'Kilómetros'), ('KILOS', 'Kilos'), ('LITROS', 'Litros'), ('METROS', 'Metros'), ('METROS_CUADRADOS', 'Metros cuadrados'), ('METROS_CUBICOS', 'Metros cúbicos'), ('TONELADAS', 'Toneladas'), ('UNITARIO', 'Unitario')], default='UNITARIO', max_length=20, verbose_name='Unidad de Compra')),
                ('ACTIVO_COMERCIAL', models.CharField(choices=[('SI', 'Sí'), ('NO', 'No')], default='SI', max_length=2, verbose_name='Activo Comercial')),
                ('ACTIVO_STOCK', models.CharField(choices=[('SI', 'Sí'), ('NO', 'No')], default='SI', max_length=2, verbose_name='Activo Stock')),
                ('ACTIVO_COMPRAS', models.CharField(choices=[('SI', 'Sí'), ('NO', 'No')], default='SI', max_length=2, verbose_name='Activo Compras')),
                ('ACTIVO_PRODUCCION', models.CharField(choices=[('SI', 'Sí'), ('NO', 'No')], default='NO', max_length=2, verbose_name='Activo Producción')),
                ('LOTEABLE', models.CharField(choices=[('SI', 'Sí'), ('NO', 'No')], default='NO', max_length=2, verbose_name='Loteable')),
                ('UNIDAD_PESO', models.CharField(blank=True, choices=[('BIDON', 'Bidón'), ('BOLSA', 'Bolsa'), ('CAJA', 'Caja'), ('FRASCO', 'Frasco'), ('GRAMOS', 'Gramos'), ('HECTAREAS', 'Hectáreas'), ('HORAS', 'Horas'), ('KILOMETROS', 'Kilómetros'), ('KILOS', 'Kilos'), ('LITROS', 'Litros'), ('METROS', 'Metros'), ('METROS_CUADRADOS', 'Metros cuadrados'), ('METROS_CUBICOS', 'Metros cúbicos'), ('TONELADAS', 'Toneladas'), ('UNITARIO', 'Unitario')], max_length=20, null=True, verbose_name='Unidad de Peso')),
                ('PESO', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, null=True, verbose_name='Peso')),
                ('UNIDAD_VOLUMEN', models.CharField(blank=True, choices=[('BIDON', 'Bidón'), ('BOLSA', 'Bolsa'), ('CAJA', 'Caja'), ('FRASCO', 'Frasco'), ('GRAMOS', 'Gramos'), ('HECTAREAS', 'Hectáreas'), ('HORAS', 'Horas'), ('KILOMETROS', 'Kilómetros'), ('KILOS', 'Kilos'), ('LITROS', 'Litros'), ('METROS', 'Metros'), ('METROS_CUADRADOS', 'Metros cuadrados'), ('METROS_CUBICOS', 'Metros cúbicos'), ('TONELADAS', 'Toneladas'), ('UNITARIO', 'Unitario')], max_length=20, null=True, verbose_name='Unidad de Volumen')),
                ('VOLUMEN', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, null=True, verbose_name='Volumen')),
                ('fchhor', models.DateTimeField(auto_now=True, verbose_name='Fecha/Hora')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('iva', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='articulos', to='articulos.iva', verbose_name='IVA')),
                ('moneda_venta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='articulos', to='articulos.moneda', verbose_name='Moneda de Venta')),
                ('idsubfamilia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articulos', to='articulos.subfamilia', verbose_name='Sub Familia')),
                ('tipo_articulo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='articulos', to='articulos.tipoarticulo', verbose_name='Tipo de Artículo')),
            ],
            options={
                'verbose_name': 'Artículo',
                'verbose_name_plural': 'Artículos',
                'db_table': 'config_articulos_maestro',
                'ordering': ['producto_id'],
            },
        ),
        migrations.CreateModel(
            name='CodigoProveedorCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_proveedor', models.CharField(help_text='Código que el proveedor usa para este artículo', max_length=100, verbose_name='Código Proveedor')),
                ('articulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='codigos_proveedor', to='articulos.articulo', verbose_name='Artículo')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='codigos_articulos', to='proveedores.proveedor', verbose_name='Proveedor')),
            ],
            options={
                'verbose_name': 'Código Proveedor Compra',
                'verbose_name_plural': 'Códigos Proveedor Compra',
                'db_table': 'config_codigoproveedorcompra',
                'ordering': ['proveedor', 'codigo_proveedor'],
                'unique_together': {('articulo', 'proveedor')},
            },
        ),
        migrations.RunSQL(
            sql="""
            -- Recrear la tabla con la foreign key correcta
            CREATE TABLE IF NOT EXISTS config_codigoproveedorcompra_new (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                codigo_proveedor VARCHAR(100) NOT NULL,
                articulo_id BIGINT NOT NULL REFERENCES config_articulos_maestro(id) ON DELETE CASCADE,
                proveedor_id BIGINT NOT NULL REFERENCES config_proveedores_maestro(id) ON DELETE CASCADE,
                UNIQUE(articulo_id, proveedor_id)
            );
            
            -- Copiar datos si la tabla original existe
            INSERT INTO config_codigoproveedorcompra_new 
            SELECT id, codigo_proveedor, articulo_id, proveedor_id 
            FROM config_codigoproveedorcompra;
            
            -- Reemplazar la tabla
            DROP TABLE IF EXISTS config_codigoproveedorcompra;
            ALTER TABLE config_codigoproveedorcompra_new RENAME TO config_codigoproveedorcompra;
            """,
            reverse_sql=migrations.RunSQL.noop
        ),
    ]
