# Generated by Django 5.2.8 on 2025-11-28 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articulos', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
            -- Recrear la tabla con la foreign key correcta (PostgreSQL compatible)
            DO $$
            BEGIN
                -- Crear nueva tabla
                CREATE TABLE IF NOT EXISTS config_codigoproveedorcompra_new (
                    id BIGSERIAL PRIMARY KEY,
                    codigo_proveedor VARCHAR(100) NOT NULL,
                    articulo_id BIGINT NOT NULL REFERENCES config_articulos_maestro(id) ON DELETE CASCADE,
                    proveedor_id BIGINT NOT NULL REFERENCES config_proveedores_maestro(id) ON DELETE CASCADE,
                    UNIQUE(articulo_id, proveedor_id)
                );
                
                -- Copiar datos si la tabla original existe
                IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'config_codigoproveedorcompra') THEN
                    INSERT INTO config_codigoproveedorcompra_new (id, codigo_proveedor, articulo_id, proveedor_id)
                    SELECT id, codigo_proveedor, articulo_id, proveedor_id 
                    FROM config_codigoproveedorcompra;
                END IF;
                
                -- Reemplazar la tabla
                DROP TABLE IF EXISTS config_codigoproveedorcompra;
                ALTER TABLE config_codigoproveedorcompra_new RENAME TO config_codigoproveedorcompra;
            END $$;
            """,
            reverse_sql=migrations.RunSQL.noop
        ),
    ]
