# Generated by Django 5.2.8 on 2025-11-28 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articulos', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
            -- Recrear la tabla con la foreign key correcta
            CREATE TABLE IF NOT EXISTS config_codigoproveedorcompra_new (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                codigo_proveedor VARCHAR(100) NOT NULL,
                articulo_id BIGINT NOT NULL REFERENCES config_articulos_maestro(id) ON DELETE CASCADE,
                proveedor_id BIGINT NOT NULL REFERENCES config_proveedores_maestro(id) ON DELETE CASCADE,
                UNIQUE(articulo_id, proveedor_id)
            );
            
            -- Copiar datos si la tabla original existe
            INSERT INTO config_codigoproveedorcompra_new 
            SELECT id, codigo_proveedor, articulo_id, proveedor_id 
            FROM config_codigoproveedorcompra;
            
            -- Reemplazar la tabla
            DROP TABLE IF EXISTS config_codigoproveedorcompra;
            ALTER TABLE config_codigoproveedorcompra_new RENAME TO config_codigoproveedorcompra;
            """,
            reverse_sql=migrations.RunSQL.noop
        ),
    ]
