# Generated by Django 5.2.8 on 2025-11-19 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articulos", "0004_remove_articulo_activo_remove_articulo_arcodigo_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="tipoarticulo",
            name="loteable",
            field=models.CharField(
                choices=[("SI", "Sí"), ("NO", "No")],
                default="NO",
                help_text="Si este tipo de artículo puede tener lotes",
                max_length=2,
                verbose_name="Loteable",
            ),
        ),
    ]
