# Generated by Django 5.2.8 on 2025-11-19 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("disponibilidades", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="disponibilidad",
            name="fecha_ingreso_sistema",
            field=models.DateField(
                blank=True,
                help_text="Fecha en que la disponibilidad ingresó al sistema",
                null=True,
                verbose_name="Fecha de Ingreso al Sistema",
            ),
        ),
        migrations.AddField(
            model_name="disponibilidad",
            name="saldo_inicial",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Saldo inicial de la disponibilidad en su moneda original",
                max_digits=15,
                verbose_name="Saldo Inicial en Moneda Original",
            ),
        ),
    ]
