# Generated by Django 5.2.8 on 2025-11-18 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CanalComercial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('activo', models.CharField(choices=[('SI', 'Sí'), ('NO', 'No')], default='SI', max_length=2, verbose_name='Activo')),
                ('fchhor', models.DateTimeField(auto_now=True, verbose_name='Fecha/Hora')),
            ],
            options={
                'verbose_name': 'Canal Comercial',
                'verbose_name_plural': 'Canales Comerciales',
                'ordering': ['nombre'],
            },
        ),
    ]

